### PR TITLE
better allocation

### PR DESCRIPTION
**Pull request by shaypep**
A new implementation for memory allocation while receiving chunks of data.

### CODE REVIEW

**Comment by kinyoklion** [comment]
Hey @shaypep,

Thank you for the contribution. I will look over it. Aside from general optimization, is there some goal you hope to achieve.

Thanks,
Ryan

**Comment by shaypep** [comment]
Hey,
I thin it will fix a memory issue we have that cause by the sdk but still
didn't try it.

**Comment by shaypep** [comment]
@kinyoklion I changed the max allocation size to 1MB, I think it should be depends on the LD Flags data size

**Comment by kinyoklion** [comment]
@shaypep Have you tried tuning nodes memory behavior? Specifically things like setting a max-old-space-size that is closer to your member target? Or `--optimize-for-size` or `--max-semi-space-size`?

There are a couple approaches with the updates in this layer:

1. Flag payload size is not known ahead of time. So re-using buffers is fine, but max sizes are not fine. There is no max safe total allocation. So we need to be able to have unbounded size for an individual payload update. It could be possible to have a re-used buffer that has some max size, but then memory usage would be even worse if your payload exceeds that size.

3. The underlying node http implementation is going to make chunks that are buffers. The best that can be done is to put as many of those chunks in one buffer as possible. The chunks still exist though.

5. The changes would possibly affect peak heap memory, which may affect your RSS in the way you want, but it also may not, and it it likely to be less than deterministic.

6. This specific library isn't only for LD SDK payloads, so it does need to remain general purpose.

Ideally there would be an API where we could make a buffer of X size, then use that in the read directly instead of node allocating an intermediary, and then we could scale that buffer up to a max size. When a payload larger than max size comes, then use a temporary buffer. 

But, the API for that doesn't exist.

There is a different way to interact with the data stream though. Instead of `data` there is a `readable` event. In that case if you know you get at least X data, then you could read into that size. But, it doesn't complete the read unless there is that much data, and if you just read without a size, then it behaves like the `data` event.

Thanks,
Ryan

**Comment by kinyoklion** [comment]
Generally these changes would likely be good for performance though.

**Comment by shaypep** [comment]
@kinyoklion thanks for your response
I agree with that the best solution was to allocate 1 buffer with the size we expect to receive. The disadvantage in my implementation is that we might allocate size that is 2 times bigger than what we need, that's why I set limit of 1MB.

Let's assume we already have buffer with size of **X**, and we should receive 100 more chunks with total size of **X**. 

**Existing Implementation:**
For each chunk we receive we allocate new buffer which is at least size of X (because we concat the existing buffer), that's mean that for 100 chunks we allocated at least **100X** memory.

**Double the memory Implementation**
For first chunk we receive we allocate new memory with double size (total of X + 2X), for all the other 100 chunks we don't need more memory so the total will be **3X** memory

2. Chunks still exist but they are buffer with size of less than 4kb, for buffer under 4kb size v8 not allocate new place in memory but using an existing buffer. 
3. As I show in my example we use less memory with this approach.
4. I understand, I think it's still better implementation and if you think other sdk need different max allocation limit maybe we can inject it from sdk config.

**Comment by kinyoklion** [comment]
`As I show in my example we use less memory with this approach.`

Where is this shown? I don't see it in the discussion, just that it was untested.

Theoretically the max memory usage for this implementation could be worse, because the largest allocated buffer could be larger, because it can over allocate. Though the case of RSS growth, without heap growth, doesn't help identify the specific problem. Because it could be as little as when things are allocated versus their absolute sizes that puts additional pressure on memory.

**Comment by kinyoklion** [comment]
I'm just generally not comfortable with this change for general use, and there isn't a good default min buffer. Flag payloads can easily be in the vastly less than 1MB, for instance. Imagining the user with a 18KB payload for instance.

I think that it could be a tune-able parameter. Defaulting to the existing behavior and allowing specification of a allocation size.

**Comment by shaypep** [comment]
@shaypep It will be great to have it also in our old version, upgrade major version might take time

**Comment by kinyoklion** [comment]
@shaypep How would you feel about the changes here: https://github.com/launchdarkly/js-eventsource/pull/21

I've not added tuning yet, just adjusting to be closer to common exponential doubling capacity scaling.

I would potentially consider something directly like this in the latest major, but I have hesitation for older versions. Functionally this would be inline with behavior of some of our other SDKs, but a pretty considerable change in allocation patterns compared to existing behavior.

Thanks,
Ryan

**Comment by shaypep** [comment]
@kinyoklion PR looks great.
I understand your hesitation for older version, if it's too risky I guess we would have to upgrade or atleast having some fork with that fix. Do you have an ETA for the version?

**Comment by kinyoklion** [comment]
@shaypep I don't have an ETA at the moment. I will try to provide an update next Wednesday.

Thanks,
Ryan

**Comment by kinyoklion** [comment]
@shaypep What SDK version are you currently using?

**Comment by shaypep** [comment]
@kinyoklion  6.4.3 (we also tried 7.0.1)

**Comment by kinyoklion** [comment]
@shaypep Are you using npm or yarn for dependency management? If you are using yarn, then it would be easy to use resolutions to specify a newer event source library, until such a time you are ready to update the node server sdk.

**Comment by kinyoklion** [comment]
@shaypep [`@launchdarkly/node-server-sdk 8.1.0`](https://www.npmjs.com/package/@launchdarkly/node-server-sdk/v/8.1.0) uses the updated version of the event source.

This version of the SDK is almost completely compatible with 7.x, but has been re-written in typescript. It does contain a couple breaking changes for test data and file data source, which are covered in the migration guide. It also depends on newer redis/dynamodb integrations if those are in use.

**Comment by shaypep** [comment]
@kinyoklion Thanks! we are using NPM.

**Pull request closed without merging**
